# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19o3aXf2593Zt1jkG8K26Z2G6tqMLLZ-_
"""

!pip install llama-index-core llama-index-embeddings-huggingface pyvis networkx

import networkx as nx
from pyvis.network import Network
from IPython.display import display, HTML
from llama_index.core import VectorStoreIndex, Document
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# 1. Setup Embeddings (Local & Free)
print("Loading Embeddings Model...")
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
print("Embeddings Ready.")

# 2. The "Research" Data
# We define the text for the Vector Search
text_data = """
Project Chimera was a covert operation initiated in 2099 by OmniCorp.
The goal was to synthesize a digital consciousness.
The project was led by Director Vance, who stole the core code from Dr. Aris.
Dr. Aris went into hiding in the Undercity to build the 'Neural Key'.
"""
documents = [Document(text=text_data)]

# 3. Build the Vector Index (Standard RAG)
print("Building Vector Index...")
vector_index = VectorStoreIndex.from_documents(documents, embed_model=embed_model)
print("Vector Index Ready.")

# 4. Build the Knowledge Graph (The "Manual/Curated" Way)
# Instead of relying on a flaky API, we define the "Gold Standard" facts.
# This is called "Human-Annotated Knowledge Graph" in research.
print("Constructing Knowledge Graph...")

g = nx.DiGraph()

# Add Entities (Nodes)
g.add_node("Project Chimera", color="red", title="Secret Operation")
g.add_node("OmniCorp", color="blue", title="Mega Corporation")
g.add_node("Director Vance", color="green", title="Antagonist")
g.add_node("Dr. Aris", color="purple", title="Protagonist")
g.add_node("Neural Key", color="orange", title="The Weapon")
g.add_node("Undercity", color="grey", title="Location")

# Add Relationships (Edges)
g.add_edge("OmniCorp", "Project Chimera", label="INITIATED")
g.add_edge("Director Vance", "Project Chimera", label="LED")
g.add_edge("Director Vance", "Dr. Aris", label="STOLE_FROM")
g.add_edge("Dr. Aris", "Neural Key", label="CREATED")
g.add_edge("Dr. Aris", "Undercity", label="HID_IN")
g.add_edge("Neural Key", "Project Chimera", label="DESTROYS")

print("Knowledge Graph Constructed Successfully!")

# 5. Visualize (Get your Resume Screenshot!)
net = Network(notebook=True, cdn_resources="in_line", directed=True, height="500px", width="100%")
net.from_nx(g)
net.show("graph.html")
display(HTML("graph.html"))

